#{% set version = "2.4.2" %}
{% set version = "2.3.1" %}

package:
  name: cryptography-vectors
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cryptography_vectors/cryptography_vectors-{{ version }}.tar.gz
  # sha256: 91d365350a2d9d5376e4efdba687c7258e31a7c8c0deefbe4f674bf0a1e87804
  # sha256: bf4d9b61dce69c49e830950aa36fad194706463b0b6dfe81425b9e0bc6644d46

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography
  license: BSD-3-Clause (or Apache 2.0)
  license_file: LICENSE.BSD
  summary: Test vectors for the cryptography package.
  dev_url: https://github.com/pyca/cryptography/tree/master/vectors
  doc_url: https://cryptography.io

extra:
  recipe-maintainers:
    - jakirkham
